# Generated by Django 4.2.27 on 2025-12-27 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eapp", "0002_categories_alter_event_img_food_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="food_items",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eapp.categories",
            ),
        ),
        migrations.AlterField(
            model_name="food_items",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
