# Generated by Django 4.2.27 on 2025-12-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eapp", "0003_food_items_category_alter_food_items_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="event",
        ),
    ]
