# Generated by Django 4.2.27 on 2025-12-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eapp", "0005_food_variants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food_items",
            name="price",
        ),
    ]
